# Generated by Django 5.1 on 2024-08-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Act1', '0002_category_remove_contact_subject_contact_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=False, upload_to='upload'),
        ),
    ]
