# Generated by Django 5.1 on 2024-08-30 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Act1', '0004_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Email', models.EmailField(default=False, max_length=254)),
                ('Contact', models.IntegerField(default=False)),
                ('date', models.DateTimeField()),
                ('msg', models.TextField(max_length=300)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Act1.category')),
            ],
        ),
    ]
